services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes: 
      - ./app/src:/usr/src/app/src:ro
      - ./app/assets:/usr/src/app/assets
      - ./app/templates:/usr/src/app/templates
      - usericons:/usr/src/app/usericons
      - ./.certs:/usr/src/app/.certs
  
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${DB_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${DB_PASSWORD}
    volumes:
    - ./app/pgadmin:/var/lib/pgadmin
  
volumes:
  usericons:

networks:
  default:
    driver: bridge