services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./config/.env
    volumes:
      - ./src:/app/src:ro
      - ./assets:/usr/src/app/assets:ro
      - usericons:/usr/src/app/usericons
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: insectos_polinizadores
      MYSQL_USER: danielxxomg
      MYSQL_PASSWORD: 40334277
      MYSQL_ROOT_PASSWORD: 40334277
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
  usericons: